Hotel/Hotel/Models/Admin.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class Admin
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        public string username { get; set; } = "Mahdy";
        [Required]
        public string password { get; set; } = "Mahdy500";
    }
}

Hotel/Hotel/Models/Enum.cs
namespace Hotel.Models
{
    public enum Enum
    {

    }
}

Hotel/Hotel/Models/ErrorViewModel.cs
namespace Hotel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hotel/Hotel/Models/Guest.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    [PrimaryKey(nameof(G_ID))]
    public class Guest
    {
        
        [Required] 
        public int G_ID { get; set; }
        [Required]
        [DisplayName("Phone number")]
        public string Phone_number { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [DisplayName("First name")]
        public string Fname { get; set; }
        [Required]
        [DisplayName("Last name")]
        public string Lname { get; set; }
        [Required]
        [DisplayName("Room number")]
        public int Room_num { get; set; }
        [Required]
        [DisplayName("Room Type")]
        public string Room_Type { get; set; }



        List<string> room_T = new List<string>()
            {
                "Single",
                "Double",
                "Suite"
            };
 

    }
  




}

Hotel/Hotel/Models/Reservation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hotel.Models
{
    public class Reservation
    {
        [Key]
        [Required]
        public int R_ID { get; set; }
        [Required]
        [ForeignKey("guest")]
        public int G_ID { get; set; }
        [Required]
        public DateTime From { get; set; }
        [Required]
        public DateTime To { get; set; }
        [Required]
        public int Num_of_night { get; set; }

        public Guest guest { get; set; }
    }
}

Hotel/Hotel/Models/Room.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hotel.Models
{
    public class Room
    {
        [Key]
        [Required]  
        public int Room_num { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        [ForeignKey("guest")]
        public int G_ID{ get; set; }

        public Guest guest { get; set; }
    }
}

Hotel/Hotel/Models/Staff.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class Staff
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string type { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Hotel/Hotel/Controllers/GuestController.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Hotel.Controllers
{
    public class GuestController : Controller
    {

        private readonly ApplicationDbContext _db;
        public GuestController(ApplicationDbContext db)
        {
            _db = db;   
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Reservation1()
        {
           

            return View();
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Reservation1(Guest guest)
        {
            var email = _db.Guests.FirstOrDefault(u => u.Email == guest.Email);
            if (email != null)
            {
                ModelState.AddModelError("Exists", "Email address Allready exists");
            }

            if (ModelState.IsValid)
            {
                _db.Guests.Add(guest);
                _db.SaveChanges();
                return RedirectToAction("Index","Home");   

            }
            return View();
        }




    }
}

Hotel/Hotel/Controllers/HomeController.cs
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hotel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hotel/Hotel/Views/Guest/Index.cshtml
<div class="d-grid gap-2">
    <a class="btn btn-lg btn-primary" asp-controller="Guest" asp-action="Reservation1">Book a Room</a>
    <a class="btn btn-lg btn-primary" type="button">Block button</a>
</div>

Hotel/Hotel/Views/Guest/Reservation1.cshtml
@model Guest

@*<form method="post" asp-controller="Guest" asp-action="Reservation1">
    <div class="border p-3 mt-4">
        
        <div class="mb-3">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control" placeholder="Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Fname">First name</label>
            <input asp-for="Fname" class="form-control" placeholder="First name" />
            <span asp-validation-for="Fname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Lname">Last name</label>
            <input asp-for="Lname" class="form-control" placeholder="Last name" />
            <span asp-validation-for="Lname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Phone_number">Phone number</label>
            <input asp-for="Phone_number" class="form-control" placeholder="Phone number" />
            <span asp-validation-for="Phone_number" class="text-danger"></span>
        </div>
        <div class="mb-3">


           

            <label asp-for="Room_Type">Select Room Type:</label>
            <select asp-for="Room_Type" class="form-control" asp-items="ViewBag.room_">
            </select>
            <span asp-validation-for="Room_Type" class="text-danger"></span>
            
        </div>
            
        
        <input type="submit" class="btn btn-primary" style="widt:150px" />
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="widt:150px">Cancel</a>
    </div>
</form>*@

@{
    var room_T = new List<string>
            {
               "Single",
               "Double",
               "Suite"
            };
    ViewData["Room"] = room_T;
}




@using (Html.BeginForm("Reservation1", "Guest", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.Fname)
        @Html.TextBoxFor(model => model.Fname, new { @class = "form-control" })
         <span asp-validation-for="Fname" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Lname)
        @Html.TextBoxFor(model => model.Lname, new { @class = "form-control" })
        <span asp-validation-for="Lname" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Phone_number)
        @Html.TextBoxFor(model => model.Phone_number, new { @class = "form-control" })
        <span asp-validation-for="Phone_number" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Room_Type)

        <select asp-for="Room_Type" class="form-control" asp-items="@(new SelectList((List<string>)ViewData["Room"]))"></select>
        <span asp-validation-for="Room_Type" class="text-danger"></span>
    </div>
    <br /><br />
    <button type="submit" class="btn btn-primary">Submit</button>
}

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
 }

Hotel/Hotel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a class="btn btn-primary" asp-controller="Guest" asp-action="Index">Book a Room!?</a>
</div>

Hotel/Hotel/Views/Room/Index.cshtml
@model Room


<form method="post" asp-action="Index">
    <div class="border p-3 mt-4">
        <div class="mb-3">
            <label for="room_type">Select Room Type:</label>
            <select id="room_type" name="room_type" asp-for="Type">
                <option value="single">Single</option>
                <option value="double">Double</option>
                <option value="triple">Triple</option>
            </select><br><br>
            <span asp-validation-for="Type" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Next</button>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
 }
 

Hotel/Hotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/BootsWatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hotel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Hotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>